# Generated by Django 3.2 on 2021-04-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountarticle',
            name='label',
        ),
    ]
