# Generated by Django 3.2 on 2021-04-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_accountarticle_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsentence',
            name='label',
            field=models.IntegerField(),
        ),
    ]
