# Generated by Django 3.2 on 2021-05-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_accountsentence_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ids_ibm',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
